media:
  input: images/blog
  output: /images/blog

content:
  - name: blog
    label: Website Blog
    type: file
    path: posts.json
    format: json
    list: true
    view:
  fields: [title, date, category]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: excerpt
        label: Subtitle / Excerpt
        type: text
        required: true
      - name: category
        label: Category
        type: string
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: cover
        label: Cover Image
        type: image
      - name: url
        label: Post URL
        type: string
        required: true
      - name: published
        label: Published
        type: boolean
        default: true
