backend:
  name: github
  repo: mberchillc/CatchDog
  branch: main
  auth_type: implicit
  app_id: Ov23lis5gu8lcaPHZD27

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Cover image", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
